/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

/**
 *
 * @author Surachai
 */
public class ForeignToThaiGUI extends javax.swing.JFrame {

    public ForeignToThaiGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CurrencyTextField1 = new javax.swing.JTextField();
        CurrencyOKButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ModeLabel14 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MoneyTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ResultTextField1 = new javax.swing.JTextField();
        ResultTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        UnitLabel = new javax.swing.JLabel();
        UnitLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("[ Select Currency ]");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("1. USD | United States");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("2. GBP | United Kingdom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("3. EUR | European Union");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("4. CHF | Switzerland");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("5. AUD | Australia");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("6. JPY | Japan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("7. MYR | Malaysia");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("8. SGD | Singapore");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("9. HKD | Hong Kong");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("10. CNY | China");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select Currency Number :");

        CurrencyOKButton1.setText("OK");
        CurrencyOKButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyOKButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("11. THB | Thailand");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Enter Money :");

        MoneyTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyTextField2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Result :");

        ResultTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultTextField1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("THB");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UnitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        UnitLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UnitLabel1.setText("UNIT");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("FOREIGN TO THAI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModeLabel14)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel13))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CurrencyOKButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CurrencyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MoneyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultTextField1)
                                    .addComponent(ResultTextField2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(UnitLabel)
                                        .addGap(332, 332, 332))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UnitLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(261, 261, 261)
                                            .addComponent(jButton1))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ModeLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrencyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(MoneyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CurrencyOKButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitLabel)
                    .addComponent(ResultTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel16)
                    .addComponent(ResultTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrencyOKButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyOKButton1ActionPerformed
        int currency = Integer.parseInt(CurrencyTextField1.getText());
        int money = Integer.parseInt(MoneyTextField2.getText());
        System.out.println("You Select Currency : " + currency);
        System.out.println("You Enter Money : " + money);
        ErrorCurrencyGUI2 start = new ErrorCurrencyGUI2();
        
        switch (currency) {
            case 1:
                float result1 = (float) (money * 31.4955);
                System.out.println("Result : " + money + " USD = " + result1 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money1 = String.valueOf(money);
                String Result1 = String.valueOf(result1);
                String Unit1 = "USD";
                ResultTextField1.setText(Money1);
                ResultTextField2.setText(Result1);
                UnitLabel1.setText(Unit1);
                break;
            case 2:
                float result2 = (float) (money * 40.7890);
                System.out.println("Result : " + money + " GBP = " + result2 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money2 = String.valueOf(money);
                String Result2 = String.valueOf(result2);
                String Unit2 = "GBP";
                ResultTextField1.setText(Money2);
                ResultTextField2.setText(Result2);
                UnitLabel1.setText(Unit2);
                break;
            case 3:
                float result3 = (float) (money * 35.3961);
                System.out.println("Result : " + money + " EUR = " + result3 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money3 = String.valueOf(money);
                String Result3 = String.valueOf(result3);
                String Unit3 = "EUR";
                ResultTextField1.setText(Money3);
                ResultTextField2.setText(Result3);
                UnitLabel1.setText(Unit3);
                break;
            case 4:
                float result4 = (float) (money * 31.2447);
                System.out.println("Result : " + money + " CHF = " + result4 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money4 = String.valueOf(money);
                String Result4 = String.valueOf(result4);
                String Unit4 = "CHF";
                ResultTextField1.setText(Money4);
                ResultTextField2.setText(Result4);
                UnitLabel1.setText(Unit4);
                break;
            case 5:
                float result5 = (float) (money * 21.8635);
                System.out.println("Result : " + money + " AUD = " + result5 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money5 = String.valueOf(money);
                String Result5 = String.valueOf(result5);
                String Unit5 = "AUD";
                ResultTextField1.setText(Money5);
                ResultTextField2.setText(Result5);
                UnitLabel1.setText(Unit5);
                break;
            case 6:
                float result6 = (float) (money * 0.28703);
                System.out.println("Result : " + money + " JPY = " + result6 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money6 = String.valueOf(money);
                String Result6 = String.valueOf(result6);
                String Unit6 = "JPY";
                ResultTextField1.setText(Money6);
                ResultTextField2.setText(Result6);
                UnitLabel1.setText(Unit6);
                break;
            case 7:
                float result7 = (float) (money * 7.5498);
                System.out.println("Result : " + money + " MYR = " + result7 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money7 = String.valueOf(money);
                String Result7 = String.valueOf(result7);
                String Unit7 = "MYR";
                ResultTextField1.setText(Money7);
                ResultTextField2.setText(Result7);
                UnitLabel1.setText(Unit7);
                break;
            case 8:
                float result8 = (float) (money * 23.0171);
                System.out.println("Result : " + money + " SGD = " + result8 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money8 = String.valueOf(money);
                String Result8 = String.valueOf(result8);
                String Unit8 = "SGD";
                ResultTextField1.setText(Money8);
                ResultTextField2.setText(Result8);
                UnitLabel1.setText(Unit8);
                break;
            case 9:
                float result9 = (float) (money * 4.0119);
                System.out.println("Result : " + money + " HKD = " + result9 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money9 = String.valueOf(money);
                String Result9 = String.valueOf(result9);
                String Unit9 = "HKD";
                ResultTextField1.setText(Money9);
                ResultTextField2.setText(Result9);
                UnitLabel1.setText(Unit9);
                break;
            case 10:
                float result10 = (float) (money * 4.5750);
                System.out.println("Result : " + money + " CNY = " + result10 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money10 = String.valueOf(money);
                String Result10 = String.valueOf(result10);
                String Unit10 = "CNY";
                ResultTextField1.setText(Money10);
                ResultTextField2.setText(Result10);
                UnitLabel1.setText(Unit10);
                break;
            case 11:
                float result11 = (float) (money * 1);
                System.out.println("Result : " + money + " THB = " + result11 + " THB");
                System.out.println("@ Thank You For Using @");
                String Money11 = String.valueOf(money);
                String Result11 = String.valueOf(result11);
                String Unit11 = "THB";
                ResultTextField1.setText(Money11);
                ResultTextField2.setText(Result11);
                UnitLabel1.setText(Unit11);
                break;
            default:
                System.out.println("ERROR - You enter the wrong currency number");
                start.setAlwaysOnTop(true);
                start.setVisible(true);
        }


    }//GEN-LAST:event_CurrencyOKButton1ActionPerformed

    private void MoneyTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyTextField2ActionPerformed
        int money = Integer.parseInt(MoneyTextField2.getText());
        System.out.println("You Enter Money : " + money);
    }//GEN-LAST:event_MoneyTextField2ActionPerformed

    private void ResultTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                 TryAgainGUI start = new TryAgainGUI();
                 start.setAlwaysOnTop(true);
                 start.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForeignToThaiGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForeignToThaiGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForeignToThaiGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForeignToThaiGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForeignToThaiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CurrencyOKButton1;
    private javax.swing.JTextField CurrencyTextField1;
    private javax.swing.JLabel ModeLabel14;
    private javax.swing.JTextField MoneyTextField2;
    private javax.swing.JTextField ResultTextField1;
    private javax.swing.JTextField ResultTextField2;
    private javax.swing.JLabel UnitLabel;
    private javax.swing.JLabel UnitLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
