/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import static java.lang.Integer.parseInt;

/**
 *
 * @author Surachai
 */
public class ForeignToForeignGUI extends javax.swing.JFrame {

   

    public ForeignToForeignGUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Currency1TextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Currency2TextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MoneyTextField3 = new javax.swing.JTextField();
        OKButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ResultTextField1 = new javax.swing.JTextField();
        ResultTextField2 = new javax.swing.JTextField();
        UnitLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        UnitLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("[ Select Currency ]");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("1. USD | United States");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("2. GBP | United Kingdom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("3. EUR | European Union");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("4. CHF | Switzerland");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("5. AUD | Australia");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("6. JPY | Japan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("7. MYR | Malaysia");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("8. SGD | Singapore");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("9. HKD | Hong Kong");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("10. CNY | China");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("11. THB | Thailand");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select Currency Number :");

        Currency1TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Currency1TextField1ActionPerformed(evt);
            }
        });

        jLabel14.setText("TO");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Enter Money :");

        OKButton1.setText("OK");
        OKButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Result :");

        ResultTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultTextField1ActionPerformed(evt);
            }
        });

        UnitLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UnitLabel2.setText("UNIT");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UnitLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UnitLabel1.setText("UNIT");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("FOREIGN TO FOREIGN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel12)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ResultTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnitLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Currency1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Currency2TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(MoneyTextField3)))
                        .addContainerGap(288, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UnitLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(106, 106, 106)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)))
                        .addGap(126, 126, 126)
                        .addComponent(jLabel17)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OKButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Currency1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Currency2TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(MoneyTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(OKButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ResultTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitLabel2)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Currency1TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Currency1TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Currency1TextField1ActionPerformed

    private void OKButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButton1ActionPerformed

        int currency1 = parseInt(Currency1TextField1.getText());
        int currency2 = parseInt(Currency2TextField2.getText());
        Float money = Float.parseFloat(MoneyTextField3.getText());

        System.out.println("First Currency : " + currency1);
        System.out.println("Second Currency : " + currency2);
        System.out.println("Money : " + money);
        
        ErrorCurrencyGUI3 start = new ErrorCurrencyGUI3();

        if (currency1 == 1 && currency2 == 1) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " USD = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
            
        } else if (currency1 == 1 && currency2 == 2) {
            float result = (float) (money * 0.79);
            System.out.println("Result : " + money + " USD = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 3) {
            float result = (float) (money * 0.90);
            System.out.println("Result : " + money + " USD = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 4) {
            float result = (float) (money * 1.0048);
            System.out.println("Result : " + money + " USD = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 5) {
            float result = (float) (money * 1.4455);
            System.out.println("Result : " + money + " USD = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 6) {
            float result = (float) (money * 108.81);
            System.out.println("Result : " + money + " USD = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 7) {
            float result = (float) (money * 4.187);
            System.out.println("Result : " + money + " USD = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 8) {
            float result = (float) (money * 1.337);
            System.out.println("Result : " + money + " USD = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 9) {
            float result = (float) (money * 7.884);
            System.out.println("Result : " + money + " USD = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 10) {
            float result = (float) (money * 6.90);
            System.out.println("Result : " + money + " USD = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 1 && currency2 == 11) {
            float result = (float) (money * 31.69);
            System.out.println("Result : " + money + " USD = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "USD";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 2 && currency2 == 1) {
            float result = (float) (money * 1.2612);
            System.out.println("Result : " + money + " GBP = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 2) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " GBP = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 3) {
            float result = (float) (money * 0.90);
            System.out.println("Result : " + money + " GBP = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 4) {
            float result = (float) (money * 1.267);
            System.out.println("Result : " + money + " GBP = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 5) {
            float result = (float) (money * 1.822);
            System.out.println("Result : " + money + " GBP = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 6) {
            float result = (float) (money * 137.02);
            System.out.println("Result : " + money + " GBP = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 7) {
            float result = (float) (money * 5.2749);
            System.out.println("Result : " + money + " GBP = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 8) {
            float result = (float) (money * 1.735);
            System.out.println("Result : " + money + " GBP = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 9) {
            float result = (float) (money * 9.88);
            System.out.println("Result : " + money + " GBP = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 10) {
            float result = (float) (money * 8.69);
            System.out.println("Result : " + money + " GBP = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 2 && currency2 == 11) {
            float result = (float) (money * 39.86);
            System.out.println("Result : " + money + " GBP = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "GBP";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 3 && currency2 == 1) {
            float result = (float) (money * 1.115);
            System.out.println("Result : " + money + " EUR = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 2) {
            float result = (float) (money * 0.886);
            System.out.println("Result : " + money + " EUR = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 3) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " EUR = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 4) {
            float result = (float) (money * 1.119);
            System.out.println("Result : " + money + " EUR = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 5) {
            float result = (float) (money * 1.612);
            System.out.println("Result : " + money + " EUR = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 6) {
            float result = (float) (money * 121.25);
            System.out.println("Result : " + money + " EUR = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 7) {
            float result = (float) (money * 4.668);
            System.out.println("Result : " + money + " EUR = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 8) {
            float result = (float) (money * 1.536);
            System.out.println("Result : " + money + " EUR = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 9) {
            float result = (float) (money * 8.746);
            System.out.println("Result : " + money + " EUR = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 10) {
            float result = (float) (money * 7.697);
            System.out.println("Result : " + money + " EUR = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 3 && currency2 == 11) {
            float result = (float) (money * 35.32);
            System.out.println("Result : " + money + " EUR = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "EUR";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 4 && currency2 == 1) {
            float result = (float) (money * 0.995);
            System.out.println("Result : " + money + " CHF = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 2) {
            float result = (float) (money * 0.791);
            System.out.println("Result : " + money + " CHF = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 3) {
            float result = (float) (money * 0.893);
            System.out.println("Result : " + money + " CHF = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 4) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " CHF = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 5) {
            float result = (float) (money * 1.44);
            System.out.println("Result : " + money + " CHF = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 6) {
            float result = (float) (money * 108.32);
            System.out.println("Result : " + money + " CHF = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 7) {
            float result = (float) (money * 4.17);
            System.out.println("Result : " + money + " CHF = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 8) {
            float result = (float) (money * 1.372);
            System.out.println("Result : " + money + " CHF = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 9) {
            float result = (float) (money * 7.812);
            System.out.println("Result : " + money + " CHF = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 10) {
            float result = (float) (money * 6.876);
            System.out.println("Result : " + money + " CHF = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 4 && currency2 == 11) {
            float result = (float) (money * 31.53);
            System.out.println("Result : " + money + " CHF = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CHF";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 5 && currency2 == 1) {
            float result = (float) (money * 0.691);
            System.out.println("Result : " + money + " AUD = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 2) {
            float result = (float) (money * 0.549);
            System.out.println("Result : " + money + " AUD = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 3) {
            float result = (float) (money * 0.620);
            System.out.println("Result : " + money + " AUD = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 4) {
            float result = (float) (money * 0.694);
            System.out.println("Result : " + money + " AUD = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 5) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " AUD = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 6) {
            float result = (float) (money * 75.17);
            System.out.println("Result : " + money + " AUD = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 7) {
            float result = (float) (money * 2.896);
            System.out.println("Result : " + money + " AUD = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 8) {
            float result = (float) (money * 0.952);
            System.out.println("Result : " + money + " AUD = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 9) {
            float result = (float) (money * 5.423);
            System.out.println("Result : " + money + " AUD = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 10) {
            float result = (float) (money * 4.772);
            System.out.println("Result : " + money + " AUD = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 5 && currency2 == 11) {
            float result = (float) (money * 21.87);
            System.out.println("Result : " + money + " AUD = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "AUD";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        }
        
        
        
        else if (currency1 == 6 && currency2 == 1) {
            float result = (float) (money * 0.0091);
            System.out.println("Result : " + money + " JPY = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 2) {
            float result = (float) (money * 0.00731);
            System.out.println("Result : " + money + " JPY = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 3) {
            float result = (float) (money * 0.00824);
            System.out.println("Result : " + money + " JPY = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 4) {
            float result = (float) (money * 0.00923);
            System.out.println("Result : " + money + " JPY = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 5) {
            float result = (float) (money * 0.013);
            System.out.println("Result : " + money + " JPY = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 6) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " JPY = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 7) {
            float result = (float) (money * 0.038);
            System.out.println("Result : " + money + " JPY = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 8) {
            float result = (float) (money * 0.0126);
            System.out.println("Result : " + money + " JPY = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 9) {
            float result = (float) (money * 0.0721);
            System.out.println("Result : " + money + " JPY = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 10) {
            float result = (float) (money * 0.0634);
            System.out.println("Result : " + money + " JPY = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 6 && currency2 == 11) {
            float result = (float) (money * 0.291);
            System.out.println("Result : " + money + " JPY = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "JPY";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        }
        
        
        
        else if (currency1 == 7 && currency2 == 1) {
            float result = (float) (money * 0.238);
            System.out.println("Result : " + money + " MYR = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 2) {
            float result = (float) (money * 0.189);
            System.out.println("Result : " + money + " MYR = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 3) {
            float result = (float) (money * 0.214);
            System.out.println("Result : " + money + " MYR = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 4) {
            float result = (float) (money * 0.239);
            System.out.println("Result : " + money + " MYR = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 5) {
            float result = (float) (money * 0.345);
            System.out.println("Result : " + money + " MYR = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 6) {
            float result = (float) (money * 25.96);
            System.out.println("Result : " + money + " MYR = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 7) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " MYR = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 8) {
            float result = (float) (money * 0.329);
            System.out.println("Result : " + money + " MYR = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 9) {
            float result = (float) (money * 1.872);
            System.out.println("Result : " + money + " MYR = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 10) {
            float result = (float) (money * 1.648);
            System.out.println("Result : " + money + " MYR = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 7 && currency2 == 11) {
            float result = (float) (money * 7.559);
            System.out.println("Result : " + money + " MYR = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "MYR";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 8 && currency2 == 1) {
            float result = (float) (money * 0.725);
            System.out.println("Result : " + money + " SGD = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 2) {
            float result = (float) (money * 0.576);
            System.out.println("Result : " + money + " SGD = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 3) {
            float result = (float) (money * 0.650);
            System.out.println("Result : " + money + " SGD = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 4) {
            float result = (float) (money * 0.729);
            System.out.println("Result : " + money + " SGD = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 5) {
            float result = (float) (money * 1.049);
            System.out.println("Result : " + money + " SGD = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 6) {
            float result = (float) (money * 78.93);
            System.out.println("Result : " + money + " SGD = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 7) {
            float result = (float) (money * 3.040);
            System.out.println("Result : " + money + " SGD = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 8) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " SGD = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 9) {
            float result = (float) (money * 5.692);
            System.out.println("Result : " + money + " SGD = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 10) {
            float result = (float) (money * 5.011);
            System.out.println("Result : " + money + " SGD = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 8 && currency2 == 11) {
            float result = (float) (money * 22.97);
            System.out.println("Result : " + money + " SGD = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "SGD";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 9 && currency2 == 1) {
            float result = (float) (money * 0.127);
            System.out.println("Result : " + money + " HKD = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 2) {
            float result = (float) (money * 0.101);
            System.out.println("Result : " + money + " HKD = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 3) {
            float result = (float) (money * 0.114);
            System.out.println("Result : " + money + " HKD = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 4) {
            float result = (float) (money * 0.128);
            System.out.println("Result : " + money + " HKD = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 5) {
            float result = (float) (money * 0.184);
            System.out.println("Result : " + money + " HKD = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 6) {
            float result = (float) (money * 13.86);
            System.out.println("Result : " + money + " HKD = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 7) {
            float result = (float) (money * 0.534);
            System.out.println("Result : " + money + " HKD = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 8) {
            float result = (float) (money * 0.175);
            System.out.println("Result : " + money + " HKD = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 9) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " HKD = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 10) {
            float result = (float) (money * 0.881);
            System.out.println("Result : " + money + " HKD = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 9 && currency2 == 11) {
            float result = (float) (money * 4.039);
            System.out.println("Result : " + money + " HKD = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "HKD";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 10 && currency2 == 1) {
            float result = (float) (money * 0.144);
            System.out.println("Result : " + money + " CNY = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 2) {
            float result = (float) (money * 0.114);
            System.out.println("Result : " + money + " CNY = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 3) {
            float result = (float) (money * 0.129);
            System.out.println("Result : " + money + " CNY = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 4) {
            float result = (float) (money * 0.145);
            System.out.println("Result : " + money + " CNY = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 5) {
            float result = (float) (money * 0.209);
            System.out.println("Result : " + money + " CNY = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 6) {
            float result = (float) (money * 15.73);
            System.out.println("Result : " + money + " CNY = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 7) {
            float result = (float) (money * 0.606);
            System.out.println("Result : " + money + " CNY = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 8) {
            float result = (float) (money * 0.199);
            System.out.println("Result : " + money + " CNY = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 9) {
            float result = (float) (money * 1.134);
            System.out.println("Result : " + money + " CNY = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 10) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " CNY = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 10 && currency2 == 11) {
            float result = (float) (money * 4.585);
            System.out.println("Result : " + money + " CNY = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "CNY";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } 
        
        
        
        else if (currency1 == 11 && currency2 == 1) {
            float result = (float) (money * 0.03174);
            System.out.println("Result : " + money + " THB = " + result + " USD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "USD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 2) {
            float result = (float) (money * 0.02453);
            System.out.println("Result : " + money + " THB = " + result + " GBP");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "GBP";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 3) {
            float result = (float) (money * 0.02825);
            System.out.println("Result : " + money + " THB = " + result + " EUR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "EUR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 4) {
            float result = (float) (money * 0.03199);
            System.out.println("Result : " + money + " THB = " + result + " CHF");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "CHF";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 5) {
            float result = (float) (money * 0.04574);
            System.out.println("Result : " + money + " THB = " + result + " AUD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "AUD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 6) {
            float result = (float) (money * 3.4826);
            System.out.println("Result : " + money + " THB = " + result + " JPY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "JPY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 7) {
            float result = (float) (money * 0.13240);
            System.out.println("Result : " + money + " THB = " + result + " MYR");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "MYR";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 8) {
            float result = (float) (money * 0.04344);
            System.out.println("Result : " + money + " THB = " + result + " SGD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "SGD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 9) {
            float result = (float) (money * 0.24917);
            System.out.println("Result : " + money + " THB = " + result + " HKD");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "HKD";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 10) {
            float result = (float) (money * 0.21850);
            System.out.println("Result : " + money + " THB = " + result + " CNY");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "CNY";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else if (currency1 == 11 && currency2 == 11) {
            float result = (float) (money * 1);
            System.out.println("Result : " + money + " THB = " + result + " THB");
            System.out.println("@ Thank You For Using @");
            String Result = String.valueOf(result);
            String Money = String.valueOf(money);
            String Unit1 = "THB";
            String Unit2 = "THB";
            ResultTextField2.setText(Result);
            ResultTextField1.setText(Money);
            UnitLabel1.setText(Unit1);
            UnitLabel2.setText(Unit2);
        } else {
            System.out.println("ERROR - Enter wrong number currency.");
            start.setAlwaysOnTop(true);
            start.setVisible(true);
        }


    }//GEN-LAST:event_OKButton1ActionPerformed

    private void ResultTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TryAgainGUI start = new TryAgainGUI();
        start.setAlwaysOnTop(true);
        start.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForeignToForeignGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForeignToForeignGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForeignToForeignGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForeignToForeignGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForeignToForeignGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Currency1TextField1;
    private javax.swing.JTextField Currency2TextField2;
    private javax.swing.JTextField MoneyTextField3;
    private javax.swing.JButton OKButton1;
    private javax.swing.JTextField ResultTextField1;
    private javax.swing.JTextField ResultTextField2;
    private javax.swing.JLabel UnitLabel1;
    private javax.swing.JLabel UnitLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
